const projects = [
    {
        title: "Pypypro (SaaS)",
        description: "Contribute to build a micro-frontend based web application with more than 16 modules where contribute on Contact, Inbox, Campaign, Calendar & Task, Pipeline, Trigger, Dashboard. Also contribute to build base structure.",
        keywords: ["React.js", "Laravel", "Node.js", "MySql", "Twilio", "Stripe", "Sendgrid", "Nylas", "Firebase"],
        link: "",
        date: "2021",
        role: "FullStack Developer",
        type: "fullstack",
    },
    {
        title: "Salespype Mobile Application",
        description: "A cross-platform mobile app by React Native Cli to manage user's basic need of web application where I developed sms, email, twilio call, push notification, calendar etc",
        keywords: ["React Native", "Redux", "Firebase", "TypeScript", "RestApi", "Twilio"],
        link: "",
        date: "2022 to till",
        role: "Mobile Developer, Team Lead",
        type: "mobile",
    },
    {
        title: "FTPO Mobile Application (iOS)",
        description: "A iOS mobile app by React Native Cli focused on social interface with some features like follow, like, share, story, save to collection, user's post timeline etc",
        keywords: ["React Native", "Redux", "Firebase", "TypeScript", "RestApi"],
        link: "",
        date: "2023 to 2024",
        role: "Mobile Developer, Team Lead",
        type: "mobile",
    },
    {
        title: "Super Local Fans",
        description: "Contribute to build a micro-frontend based web application to make campaign to post into social media by recording videos",
        keywords: ["React.js", "Vite", "Next.js"],
        link: "",
        date: "2024",
        role: "Frontend Developer, Front-end Team Lead",
        type: "frontend",
    },
    {
        title: "Connect Social Mobile Application",
        description: "A cross-platform mobile app by React Native Cli to manage user's basic need of web application where bunches of module with drag and drop and animation",
        keywords: ["React Native", "Redux", "Firebase", "TypeScript", "RestApi", "GraphQl", "Rtk-Query"],
        link: "",
        date: "2025 to till",
        role: "Mobile Developer, Team Lead",
        type: "mobile",
    },
    {
        title: "Video Making Manager",
        description: "Developed a simple tools from branding user's products by recording videos like reel and build campaign based on those videos. Create a widget or embed code to use any platform",
        keywords: ["React"],
        link: "",
        date: "2019-2021",
        role: "Frontend Developer",
        type: "frontend",
    },
    {
        title: "Reward mobile application",
        description: "A cross platform mobile application by React native to maintain an organization's reward system.",
        keywords: ["React Native", "Context Api"],
        link: "",
        date: "2020",
        role: "Mobile Developer",
        type: "mobile",
    },
    {
        title: "Chatbot Ai",
        description: "Build a support tool to communicate with visitor via widget or embed code about brand and it's products and also generate lead information from conversation.",
        keywords: ["React.js", "Vite", "TypeScript", "RestApi", "Chatgpt", "Python"],
        link: "",
        date: "2025",
        role: "Frontend Developer, Lead",
        type: "frontend",
    },
    {
        title: "Nordisk CRM",
        description: "Contribute to build a micro-frontend based web application with more than 7 modules. Contribute to setup base structure.",
        keywords: ["React.js", "Vite", "TypeScript", "GraphQl", "Multi-language", "Permission Based", "Micro-frontend"],
        link: "",
        date: "2025",
        role: "Frontend Developer, Lead",
        type: "frontend",
    },
    {
        title: "Map Contact Mobile Application",
        description: "A cross platform mobile application by React native for map contact web application to manage user's basic need like contact, inbox, conversation, contact searching from map etc",
        keywords: ["React Native", "Redux", "Google Map", "Firebase"],
        link: "",
        date: "2021",
        role: "Mobile Developer",
        type: "mobile",
    },
    {
        title: "Earn5Star",
        description: "Manage Review, Rating, Scraping data from URL, Manage Campaign by Twilio and Sendgrid",
        keywords: ["Laravel", "MySql", "node.js", "Twilio", "Sendgrid"],
        link: "",
        date: "2018 to 2019",
        role: "FullStack Developer",
        type: "fullstack",
    },
    {
        title: "Call Tracking",
        description: "Manage Lead by real twilio call.Set trigger on ongoing call duration to track lead value. Manage Campaign by Twilio",
        keywords: ["Laravel", "MySql", "node.js", "Twilio"],
        link: "",
        date: "2019",
        role: "FullStack Developer",
        type: "fullstack",
    },
    {
        title: "Super Shop Management",
        description: "Develop full super shop management system with hrm, inventory, pos system",
        keywords: ["Laravel", "MySql"],
        link: "",
        date: "2019 to 2021",
        role: "FullStack Developer",
        type: "fullstack",
    },
];

const tabs = ["all", "mobile", "frontend", "backend"];

export {projects, tabs}