const skills = [
    { name: "React", icon: "⚛️" },
    { name: "React Native", icon: "⚛️" },
    { name: "Next.js", icon: "⏭️" },
    { name: "TailwindCSS", icon: "🌊" },
    { name: "JavaScript", icon: "🟨" },
    { name: "TypeScript", icon: "📘" },
    { name: "Redux", icon: "🌀" },
    { name: "Rtk", icon: "🧰" },
    { name: "Zustand", icon: "🐻" },
    { name: "Node.js", icon: "🟢" },
    { name: "Express.js", icon: "🚂" },
    { name: "Nest.js", icon: "🐦‍🔥" },
    { name: "Prisma", icon: "🔷" },
    { name: "MySql", icon: "🐬" },
    // { name: "NPM", icon: "📦" },
    // { name: "PNPM", icon: "🧩" },
    // { name: "Git", icon: "🔧" },
    // { name: "GitHub", icon: "🐱" },
    // { name: "Figma", icon: "🎨" },
    // { name: "Turborepo", icon: "🚀" },
    // { name: "Deno", icon: "🦕" },
    { name: "PostgreSQL", icon: "🐘" },
    { name: "MySQL", icon: "🛢️" },
    // { name: "MongoDB", icon: "🍃" },
    // { name: "Discord.js", icon: "💬" },
    { name: "Rollup", icon: "📦" },
    { name: "CI/Cd", icon: "🔁" },
    { name: "Docker", icon: "🐳" },
    // { name: "Vercel", icon: "▲" },
    // { name: "Astro", icon: "⭐" },
    { name: "ESLint", icon: "🔍" },
];

export {skills};