const skills = [
    { name: "React", icon: "⚛️" },
    { name: "React Native", icon: "⚛️" },
    { name: "Next.js", icon: "⏭️" },
    { name: "TailwindCSS", icon: "🌊" },
    { name: "JavaScript", icon: "🟨" },
    { name: "TypeScript", icon: "📘" },
    { name: "Redux", icon: "🌀" },
    { name: "Rtk", icon: "🧰" },
    { name: "Zustand", icon: "🐻" },
    { name: "Node.js", icon: "🟢" },
    { name: "Express.js", icon: "🚂" },
    { name: "Nest.js", icon: "🐦‍🔥" },
    { name: "Prisma", icon: "🔷" },
    { name: "MySql", icon: "🐬" },
    { name: "NPM", icon: "📦" },
    // { name: "PNPM", icon: "🧩" },
    { name: "Git", icon: "🔧" },
    { name: "GitHub", icon: "🐱" },
    // { name: "Figma", icon: "🎨" },
    // { name: "Turborepo", icon: "🚀" },
    // { name: "Deno", icon: "🦕" },
    { name: "PostgreSQL", icon: "🐘" },
    { name: "S3 Aws", icon: "🛢️" },
    { name: "Minio", icon: "🛢️" },
    // { name: "MongoDB", icon: "🍃" },
    { name: "Discord.js", icon: "💬" },
    { name: "Rollup", icon: "📦" },
    { name: "CI/CD", icon: "🔁" },
    { name: "Docker", icon: "🐳" },
    // { name: "Vercel", icon: "▲" },
    // { name: "Astro", icon: "⭐" },
    { name: "ESLint", icon: "🔍" },
    { name: "Husky", icon: "🔍" },
    { name: "VS Code", icon: "🔍" },
    { name: "XCode", icon: "🔍" },
    { name: "Android Studio", icon: "🔍" },
];

const integrations = [
  { name: "Twilio", icon: "📞" },
  { name: "WhatsApp API", icon: "💬" },
  { name: "Facebook APIs", icon: "📘" },
  { name: "Gmail API", icon: "📧" },
  { name: "Google Maps", icon: "🗺️" },
  { name: "Stripe", icon: "💳" },
  { name: "SendGrid", icon: "📨" },
  { name: "Postmark", icon: "✉️" },
  { name: "Nylas", icon: "🔗" },
  { name: "Nexmo (Vonage)", icon: "📡" },
  { name: "Firebase", icon: "🔥" },
  { name: "Firestore", icon: "🗃️" },
  { name: "AWS S3", icon: "☁️" },
  { name: "MinIO", icon: "🗄️" },
  { name: "SMTP", icon: "📮" },
  { name: "Zapier", icon: "⚡" },
  { name: "ChatGPT / OpenAI", icon: "🤖" },
  { name: "SlyBroadcast", icon: "📢" },
];

export {skills, integrations};